dist: trusty
language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install coverage
  - pip install flask
  - pip install flask_restplus
  - pip install scipy
addons:
  sonarcloud:
    organization: "montezuma93-github" # the key of the org you chose at step #3
    token:
      secure: "adfa280c3ad105eb6ee90a331610f38d9315b3cc" # encrypted value of your token
after_success: coverage report
# command to run tests
script:
  - coverage run -m unittest
  - coverage xml
  # other script steps might be done before running the actual analysis
  - sonar-scanner
